site_name: Flightpath

repo_name: Gufran/flightpath
repo_url: https://github.com/Gufran/flightpath

site_url: https://docs.flightpath.xyz/
site_description: Flightpath Edge Proxy Documentation
site_author: Mohammad Gufran
docs_dir: site

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Indigo'
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - type: github-alt
      link: https://github.com/Gufran
    - type: twitter
      link: https://twitter.com/freatbeater

markdown_extensions:
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown.extensions.def_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Route Discovery: route-discovery.md
  - Envoy Configuration: envoy-configuration.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Observability: observability.md
  - Error Messages: error-messages.md